name: deploy-auth-api

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Verify Java
        run: java --version

      - name: Verify Maven
        run: mvn --version

      - name: Build Quarkus application
        run: mvn clean package

      - name: Build image with Podman
        run: podman build -t cqrs-api:1.0 .

      - name: Import image into K3s
        run: |
          podman save cqrs-api:1.0 -o cqrs-api.tar
          sudo k3s ctr images import cqrs-api.tar

      - name: Deploy to Kubernetes
        run: |
          export KUBECONFIG=$HOME/.kube/config
          kubectl apply -n cqrs-lab -f k8s/

      - name: Restart deployment
        run: |
          kubectl rollout restart deployment cqrs-api -n cqrs-lab
